package pedidosfarmaceuticosapp.ui;

import pedidosfarmaceuticosapp.model.Order;
import javax.swing.JOptionPane;


public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlHome = new javax.swing.JLabel();
        jlMedicamento = new javax.swing.JLabel();
        txtMedicinename = new javax.swing.JTextField();
        jlType = new javax.swing.JLabel();
        cbMedicineType = new javax.swing.JComboBox<>();
        jlUsers = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jlDistribuitor = new javax.swing.JLabel();
        rbCofarma = new javax.swing.JRadioButton();
        rbEmpsephar = new javax.swing.JRadioButton();
        rbCemefar = new javax.swing.JRadioButton();
        jlBranch = new javax.swing.JLabel();
        chkPrincipal = new javax.swing.JCheckBox();
        chkSecundaria = new javax.swing.JCheckBox();
        btnBorrar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Farmaceutica");

        jlHome.setText("Home");

        jlMedicamento.setText("Nombre del medicamento:");

        txtMedicinename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicinenameActionPerformed(evt);
            }
        });

        jlType.setText("Tipo de medicamento:");

        cbMedicineType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Analgésico", "Analéptico", "Anestésico", "Antálgico", "Antidepresivo", "Antibiótico" }));

        jlUsers.setText("Usuarios");

        jLabel1.setText("Cantidad: ");

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        jlDistribuitor.setText("Distribuidor: ");

        rbCofarma.setText("Cofarma");

        rbEmpsephar.setText("Empsephar");

        rbCemefar.setText("Cemefar");

        jlBranch.setText("Sucursal: ");

        chkPrincipal.setText("Principal");
        chkPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPrincipalActionPerformed(evt);
            }
        });

        chkSecundaria.setText("Secundaria");

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnBorrar)
                        .addGap(152, 152, 152)
                        .addComponent(btnConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlHome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlMedicamento)
                                .addComponent(jlType)
                                .addComponent(jLabel1)
                                .addComponent(jlDistribuitor)
                                .addComponent(jlBranch)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMedicinename, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMedicineType, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbCofarma)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbEmpsephar)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbCemefar))
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkPrincipal)
                                        .addGap(18, 18, 18)
                                        .addComponent(chkSecundaria))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jlUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlMedicamento)
                    .addComponent(txtMedicinename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlType)
                    .addComponent(cbMedicineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDistribuitor)
                    .addComponent(rbCofarma)
                    .addComponent(rbEmpsephar)
                    .addComponent(rbCemefar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBranch)
                    .addComponent(chkPrincipal)
                    .addComponent(chkSecundaria))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar)
                    .addComponent(btnConfirmar))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicinenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicinenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicinenameActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void chkPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPrincipalActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

    txtMedicinename.setText("");
    cbMedicineType.setSelectedIndex(0);
    txtQuantity.setText("");
    buttonGroup1.clearSelection();
    chkPrincipal.setSelected(false);
    chkSecundaria.setSelected(false);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        try {
        // Validaciones
        String medicineName = txtMedicinename.getText().trim();
        if (medicineName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del medicamento no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!medicineName.matches("[a-zA-Z0-9 ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre del medicamento solo puede contener caracteres alfanuméricos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String medicineType = (String) cbMedicineType.getSelectedItem();
        if (medicineType.equals("Seleccione")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un tipo de medicamento", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String quantityText = txtQuantity.getText().trim();
        if (quantityText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cantidad no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int quantity;
        try {
            quantity = Integer.parseInt(quantityText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser un número positivo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String distributor = null;
        if (rbCofarma.isSelected()) {
            distributor = "Cofarma";
        } else if (rbEmpsephar.isSelected()) {
            distributor = "Empsephar";
        } else if (rbCemefar.isSelected()) {
            distributor = "Cemefar";
        }
        if (distributor == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un distribuidor", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!chkPrincipal.isSelected() && !chkSecundaria.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar al menos una sucursal", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el pedido
        Order order = new Order();
        order.setMedicineName(medicineName);
        order.setMedicineType(medicineType);
        order.setQuantity(quantity);
        order.setDistributor(distributor);
        order.setMainBranch(chkPrincipal.isSelected());
        order.setSecondaryBranch(chkSecundaria.isSelected());

        // Abrir ventana de confirmación
        ConfirmationWindow confirmationWindow = new ConfirmationWindow(order);
        confirmationWindow.setVisible(true);
        this.dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbMedicineType;
    private javax.swing.JCheckBox chkPrincipal;
    private javax.swing.JCheckBox chkSecundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlBranch;
    private javax.swing.JLabel jlDistribuitor;
    private javax.swing.JLabel jlHome;
    private javax.swing.JLabel jlMedicamento;
    private javax.swing.JLabel jlType;
    private javax.swing.JLabel jlUsers;
    private javax.swing.JRadioButton rbCemefar;
    private javax.swing.JRadioButton rbCofarma;
    private javax.swing.JRadioButton rbEmpsephar;
    private javax.swing.JTextField txtMedicinename;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
